name: Deploy Web Prototype

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: yarn install

    - name: Build Web App
      run: |
        yarn vite build
      env:
        NODE_ENV: production

    # الخطوة دي هتورينا الملفات فين بالظبط عشان نتأكد 100%
    - name: Debug File Structure
      run: ls -R books/dist_electron/build/src/ || ls -R dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-prototype
        # تعديل المسار للمكان اللي إنت قلته
        path: books/dist_electron/build/src/