name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

# تصريح بالصلاحيات للنشر على Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: yarn install

    - name: Build Web App
      run: yarn vite build
      env:
        NODE_ENV: production

    # خطوة النشر الحقيقية
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # المسار اللي إنت اكتشفته بنفسك
        path: src/dist/

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4